version: "3.5"
services:
  emby:
    image: emby/embyserver_arm32v7:latest
    container_name: emby
    restart: always
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ./config:/config # Configuration directory
      - ./movies:/mnt/share1 # Media directory
      - ./series:/mnt/share2 # Media directory
    devices:
      - /dev/dri/:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    networks:
      docker:
    logging:
      options:
        max-size: 100M

networks:
  docker:
